services:
  postgres:
    image: postgres:15
    container_name: projeto-bd-ufma-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: senhamuitoforte123
      POSTGRES_DB: sistema_chamados
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: